[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[lib]
name = "gui"
path = "src/libs.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
