name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run test #1
      run: cd tempconvert && cargo test --verbose --workspace
    - name: Run test #2
      run: cd tempconvert && cargo test --verbose --workspace
    - name: Run test #3
      run: cd fibo && cargo test --verbose --workspace
    - name: Run test #4
      run: cd xmasdays && cargo test --verbose --workspace
    - name: Run test #5
      run: cd mathm3 && cargo test --verbose --workspace

